### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by OlivierJM** [SparkEdUAB/SparkEd-Dev#2]
Progress of SparkEd and Next Steps in this thread @abnios

**Comment by abnios** [comment]
Okay Oliver Thank you, So can you breif me the latest updates and newly incorporated things and any other thing to have common understanding of the progress please.

**Comment by abnios** [comment]
Great, what about the Sync that you worked on? the final product of the App???

**Comment by OlivierJM** [comment]
Yes the Sync is working but it needs enhancements like url settings checking what already existed there, and few other things but I liked how it is working, once you clone you will be able to see how it working.

**Comment by abnios** [comment]
Yes, I sawed the source code..., That is great Oliver, You did a nice work. So can we list the things that we need to work on? what about the App, is it linked to the server and can fetch resources from the server?

**Comment by OlivierJM** [comment]
We can list what the features we need to focus on next and what we might not need.

**Comment by abnios** [comment]
great, I was trying to build the app, as you suggested me I opened using Android studio, then it asked me to update the android studio and gradle, I updated the android studio to v-3 but can't solve the gradle problem, that was why I kept silent, can't finalize some update that requires. do you incorporated setting for the app, like changing the server url, and the like in the app?

**Comment by OlivierJM** [comment]
Not there is no settings page so far, but I feel it is very important to have it, to allow users to change the server url.
I think this time most of the errors are cleaned, you can try and pull and see it they can be fixed, Android Studio should help much with it.

**Comment by abnios** [comment]
Okay... I will try the latest one.
So what are the remaining features to be incorporated, the first is the internationalization, the UI looking,  finalizing the sync, pdf and document crawling (apache Solrs) and what??

**Comment by OlivierJM** [comment]
We can start with those if they are the important ones, When is the SparkEd likely to start being used? it would help to know from users' perspective what issue they might find so that we start by making it best for users.
I will add those to the [project here  ](https://github.com/SparkEdUAB/SparkEd-Dev/projects/1)

**Comment by abnios** [comment]
we planned to use in the coming September. we planned to deploy the latest version and encode resources in this august half (max,  assuming encoding is a two weeks task).

**Comment by OlivierJM** [comment]
Okay that sounds great, that we will be so busy after September when it starts getting used.

**Comment by OlivierJM** [comment]
So let's keep these features on the line, we fix and test what we have and then deploy it.

**Comment by abnios** [comment]
Okay, let's start with the internationalization, then we will continue to the next features. so is the master branch currently stable? can I clone that and start working on that??

**Comment by OlivierJM** [comment]
Yeah it is stable, you can clone and see how it is, you can always let me know if you have questions.

**Comment by abnios** [comment]
Okay, Let us discuss issues related to internationalization on that.

**Comment by OlivierJM** [comment]
You can initiate the conversation there. this https://github.com/SparkEdUAB/SparkEd-Dev/projects/1 . ?

**Comment by abnios** [comment]
Yes I saw that, I am trying to clone the project

**Comment by OlivierJM** [comment]
Cool, Let me know how if you have any errors.
