### ISSUE TITLE
Internalization

### ISSUE THREAD

**Issue by OlivierJM** [SparkEdUAB/SparkEd-Dev#3]
Users need to be able to access the application in their own language

If there will need, we will discuss about internalisation on this thread.

**Comment by abnios** [comment]
So let us proceed from the previously tested internationalization library i18n? are we going to use a defined number of languages? and how many, I am asking this even preparing the json file(preparing the json file is also our task) and change buttons need to be considered.

**Comment by OlivierJM** [comment]
Yeah what languages are we considering in this case and which ones are a priority?

**Comment by abnios** [comment]
lets place use English as a default, place an option to have about four or five alternatives, (Only create the key values and then anytime anyone can replace the equivalent value for each language), also let's have a setting to enable and disable( show/hide) the language buttons or selections.

**Comment by abnios** [comment]
can we have an option to localize the contents too?? what do you think Oliver??

**Comment by OlivierJM** [comment]
Alright, that sounds great Abi, we will need a proper interface to accomodate that, we might need UI redesign.
Localizing contents might not be possible considering that some are videos, pdfs, and images.

**Comment by abnios** [comment]
I was not thinking about Localizing contents Oliver, but option to feed contents as per the localization types,   we are not expected to worry about the content, but what if we can prepare a place to put contents for each language, just an option.

**Comment by OlivierJM** [comment]
Ohhh I see, you mean categorizing contents according to the localization ? that would be great

**Comment by OlivierJM** [comment]
@abnios I have started working on this issue, kindly prepare the translations that are needed and let me know the languages that will be needed.

**Comment by OlivierJM** [comment]
On the pages like Courses and Units that allows Admins to change the titles, translations won't be possible for those since we don't exactly what the titles will be, however translations will be added on other parts.

**Comment by OlivierJM** [comment]
This just needs more vocabularies added in the json file.
