### ISSUE TITLE
Sync Address

### ISSUE THREAD

**Issue by OlivierJM** [SparkEdUAB/SparkEd-Dev#9]
Courses and Topics syncing from a wrong address
@abnios can you confirm the address where it is syncing from ?

**Comment by abnios** [comment]
@OlivierJM the aAutoSync code gives the url to sync from    http://52.42.16.134/ with a school name kijabe
but the IP can't respond on a browser

**Comment by OlivierJM** [comment]
That is the old code, I am yet to remove it after confirming the new sync, It should sync from this address http://13.232.61.192/ 
I just tested it, I just need to properly connect the scripts that sync the resources so that they too can automatically sync.

**Comment by abnios** [comment]
I tested using this Ip, it says already synced, may  I reset the meteor and try syncing again???

**Comment by OlivierJM** [comment]
No obvious it has already synced, I am still working on it but it is basically working, I will polish it up,

**Comment by OlivierJM** [comment]
I can confirm that the Syncing is working on the following address http://13.232.61.192/
we will however need to make the server address dynamic so that the admin can specify the address to sync from.

**Comment by OlivierJM** [comment]
The bug is fixed and am closing the issue
